#!/bin/bash

session=ttyfire

if ! tmux attach-session -t "$session" 2>/dev/null
then
	d=/tmp/ttyfire-dirty-startup
	readarray -ts 4 channels < ~/.ttyfire
	(
		echo "tmux set renumber-windows on"
		echo "tmux bind 'F1' kill-session"
		echo "tmux bind 'F12' kill-window"
	) > "$d"
	for i in "${channels[@]}"
	do
		echo "tmux new-window \"ttyfire_new \\\"$i\\\"\""
		echo 'sleep 0.5'
	done >> "$d"
	chmod u+x "$d"
	tmux new-session -s "$session" "$d"
fi
