#!/bin/bash

[[ -z "$1" ]] && { echo "Usage: $(basename "$0") <room>" >&2; exit 1; }

tmp=$(mktemp -d)
trap 'cd /; rm -Rf "$tmp"' EXIT
cd "$tmp"

mkfifo 'in'

cat ~/.screenrc - >.screenrc <<EOF
caption string '%{= bk}%t%{= dd}'

split
resize max
screen -t "$1" campfire_room "$1"
# For testing purposes:
#screen -t out bash -c 'while sleep 0.5; do cat in; done'
focus
resize +5
screen -t "Input" ttyfire_pipefiller
EOF

screen -c .screenrc
