#!/bin/bash

[[ -z "$1" ]] && { echo "Usage: $(basename "$0") <room>" >&2; exit 1; }
[[ -z "$TMUX" ]] && { echo "Must be run inside of tmux." >&2; exit 1; }

room=$1
base="/tmp/campfire/rooms/$room"

mkdir -p "$base"

(
	tmux set status on
	tmux set status-left " -- Campfire -- "
	tmux rename-window "$room"
	tmux set status-right ""
	tmux set window-status-current-fg yellow
	tmux set window-status-current-bg black
	tmux set status-fg white
	tmux set status-bg black
	tmux set pane-active-border-fg default
	tmux set history-limit 50000
	tmux split-window -l 5 "ttyfire_pipefiller \"$base/in\""
) >/dev/null

clear

campfire_room "$base/in" "$room" 2>&1 | tee "$base/log"
